- hosts: all
  become: true
  roles:
    - docker

- hosts: develop
  become: true
  roles:
    - users
    - java
    - jenkins
    - sonarqube
    - sshClientJenkins

- hosts: test
  become: true
  roles:
    - sshHost

- hosts: staging
  become: true
  roles:
    - sshHost

- hosts: prod1
  become: true
  roles:
    - sshHost
    - swarm-manager

- hosts: prod2
  become: true
  roles:
    - sshClient
    - swarm-worker
