- hosts: jenkins
  become: true
  roles:
    - jenkins
    - docker
    - sonarqube

- hosts: test
  become: true
  roles:
    - docker

- hosts: staging
  become: true
  roles:
    - docker

- hosts: prod
  become: true
  roles:
    - docker