- hosts: all
  become: true
  roles:
    - docker

- hosts: develop
  become: true
  roles:
    - java
    - jenkins
    - sonarqube

- hosts: test
  become: true
  roles:
    - java

- hosts: staging
  become: true
  roles:
    - java

- hosts: prod1
  become: true
  roles:
    - java
    - swarm-manager

- hosts: prod2
  become: true
  roles:
    - java
    - swarm-worker