- name: determine swarm status
  shell: "docker info | egrep '^Swarm: ' | cut -d ' ' -f2"
  register: swarm_status

- name: retrieve swarm worker token from manager host
  command: "docker swarm join-token -q worker"
  delegate_to: "prod1"
  register: token 

- name: Join swarm cluster as worker
  shell: "docker swarm join --token {{ token.stdout_lines }} {{ hostvars['prod1']['ansible_host'] }}:2377"
  when: "'active' not in swarm_status.stdout_lines"