- name: determine swarm status
  shell: "docker info | egrep '^Swarm: ' | cut -d ' ' -f2"
  register: swarm_status

- name: retrieve swarm worker token from manager host
  shell: "ssh -o StrictHostKeyChecking=no vagrant@10.10.0.21 docker swarm join-token -q worker"
  register: token
  become: no


- name: Join swarm cluster as worker
  shell: "docker swarm join --token {{ token.stdout_lines[0] }} {{ hostvars['prod1']['ansible_host'] }}:2377"
  when: "'inactive' in swarm_status.stdout_lines[0]"