version: '3.1'
services:
  app:
    build:
      context: ./docker
    ports:
      - 80:80
    volumes:
      - ./:/var/www      
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "example"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
