version: '3.1'
services:
  app:
    build:
      context: ./docker
    container_name: app
    ports:
      - 80:80
    volumes:
      - .:/var/www/html      
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "example"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
