# Read the documentation https://github.com/Orbitale/EasyImpressBundle#yml-reference for more details about yaml options
data:
    # In seconds
    transition-duration: 1000

slides:
#    - content: '0'
#      attr:
#      data:
#          x: 100
#          y: 100
#          z: 0
#          rotate-x: 0
#          rotate-y: 0
#          rotate-z: 0
#
#    - content: '1'
#      attr:
#        style: "padding: 0; margin: 0;"
#      data:
#
#          x: 0
#          z: 0
#          "rotate-y": 0
#
#    - content: '2'
#      attr:
#          style: "background-color: #333; width: 200px; height: 200px; padding: 0; margin: 0; line-height: 200px;"
#      data:
#          x: 100
#          z: -100
#          rotate-y: 90
#
#    - content: '3'
#      attr:
#          style: "background-color: #666; width: 200px; height: 200px; padding: 0; margin: 0; line-height: 200px;"
#      data:
#          x: 0
#          z: -200
#          "rotate-y": 180
#
#    - content: '4'
#      attr:
#          style: "background-color: #999; width: 200px; height: 200px; padding: 0; margin: 0; line-height: 200px;"
#      data:
#          x: -100
#          z: -100
#          "rotate-y": 270
#
#    - content: '5'
#      attr:
#          style: "background-color: #aaa; width: 200px; height: 200px; padding: 0; margin: 0; line-height: 200px;"
#      data:
#          x: 0
#          y: -100
#          z: -100
#          "rotate-y": 360
#          "rotate-x": 90
#
#    - content: '6'
#      attr:
#          style: "background-color: #ccc; width: 200px; height: 200px; padding: 0; margin: 0; line-height: 200px;"
#      data:
#          x: 0
#          y: 100
#          z: -100
#          "rotate-y": 360
#          "rotate-x": -90
