- name: Add an Apt signing key for Jenkins repository
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present

- name: Add repositories to the list
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: jenkins
  with_items:
    - ppa:webupd8team/java
    - deb http://pkg.jenkins.io/debian-stable binary/

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: Update repositories and install packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - oracle-java8-installer
    - jenkins