- name: Add an Apt signing key for Jenkins repository
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present

- name: Add repositories to the list
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://pkg.jenkins.io/debian-stable binary/

- name: Update repositories and install packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - jenkins